# Generated by Django 5.2.5 on 2025-08-11 17:26

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
