# Generated by Django 5.2.5 on 2025-08-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_chapterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
