# Generated by Django 5.2.5 on 2025-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_chapterimage_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterimage',
            name='position',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
