# Generated by Django 5.2.5 on 2025-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
