# Generated by Django 5.2.5 on 2025-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='terms', to='books.category'),
        ),
    ]
